### ISSUE TITLE
allow style override for root component

### ISSUE THREAD

**Issue by vutran** [vutran/omnibar#1]
No way to set `style` for the `<Omnibar/>` component. 

Ref: https://github.com/vutran/omnibar/blob/master/src/Omnibar.tsx#L145

**Comment by adnasa** [comment]
Surely the solution to setting a style on the root would be pretty easy,
but this looks to me like there are multiple sides to the "issue"

1. we pass down multiple styles depending on the context and this has paved way to really confusing prop-names
    - `rowStyle`: there is no reference to __which__ row we want to put our styles into
    - `resultStyle`: Do we mean the entire list as a result or the specific result we are focusing on?
    - `inputStyle`: Okay, this time our naming points to the input, but we're not there yet
2. the second issue here is that this styles are passed down directly as objects, which could lead to unecessary re-renders implicitly whenever another prop passed down has changed (and hence, we can accidently by-pass the `shouldComponentUpdate` on the consumer side.
3. A cause to a problematic re-render is that we [compose our style objects](https://github.com/vutran/omnibar/blob/master/src/ResultsItem.tsx#L68) within the component => another re-rendering
4. General question; I generally dislike the `style` prop, because this is an object and induces that devs use `css in js`. Also, because this is an object, it can lead to unecessary renders due to referential equality as pointed above. Surely there is another way to accept styling from the consumer without having to resort to `style`?

---

hmm...
Do you want to do something about this?

**Comment by adnasa** [comment]
let's close this for now.
We already have a good follow up on my other concerns 😉
